[build]
  command = "npm install"
  functions = "netlify/functions"

[functions]
  directory = "src/lambda/"
  node_bundler = "esbuild"

[functions."api"]
  included_files = ["src/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/"
  status = 200