[build]
  command = "npm install"

[functions]
  directory = "src/lambda/"
  node_bundler = "esbuild"

[functions."api"]
  included_files = ["src/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200